[package]
name = "actix-api"
version = "0.1.0"
authors = ["Joaqu√≠n Gumucio L. <jjgumucio@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
